### ISSUE TITLE
Doesn't work in a React Native app

### ISSUE THREAD

**Issue by TsuryKnox** [mguellsegarra/myopic-app-switcher#1]
I tried using it, but the overlay/blur will apply for a second and then it will return to the original content.

**Comment by mguellsegarra** [comment]
Hi! Have you seen the readme? There's a big warning saying that this behaviour is only working in API 26 devices. Also, there are a lot of manufacturers that have different behaviours and tweaks that alter this functionalitiy.

I would be glad to see if anybody comes with an improvement for this library, so if you're interested, you can make your own research and open a PR! That's the open source magic :)

**Comment by TsuryKnox** [comment]
Got it, thanks :)
